"""Smart project scanner — respects .gitignore and filters generated files."""

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

MAX_FILE_KB = 200  # default per-file size limit

# Files to always skip regardless of language (generated, lock files, declarations)
_GENERATED_EXACT = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Packages.lock.json",
    "packages.lock.json",
    "npm-shrinkwrap.json",
}

_GENERATED_SUFFIXES = (
    ".min.js",
    ".min.css",
    ".bundle.js",
    ".d.ts",           # TypeScript declaration files — generated by tsc
    ".generated.cs",   # C# source generators
    ".Designer.cs",    # WinForms / ASP.NET designer
    ".g.cs",           # Roslyn source generators
    ".AssemblyInfo.cs",
)


@dataclass
class ScanResult:
    files: list[str] = field(default_factory=list)
    files_by_language: dict[str, int] = field(default_factory=dict)
    skipped_gitignore: int = 0
    skipped_too_large: int = 0
    skipped_generated: int = 0
    total_discovered: int = 0
    estimated_size_kb: int = 0


def scan_project(
    project_path: str,
    languages: list[str] | None = None,
    max_file_kb: int = MAX_FILE_KB,
) -> ScanResult:
    """Scan a project directory and return what would be indexed.

    Discovery strategy (three tiers):
    1. git ls-files — for git repos; respects all .gitignore sources automatically
    2. pathspec — for non-git repos with a .gitignore file
    3. os.walk + DEFAULT_EXCLUDES — last resort for bare directories

    Post-filters: extension, file size, generated-file patterns.
    """
    from rag_server.core.project import (
        ALL_CODE_EXTENSIONS,
        DEFAULT_EXCLUDES,
        LANGUAGE_EXTENSIONS,
        extension_to_language,
        load_ragignore,
    )

    root = Path(project_path).resolve()

    # .ragignore entries: simple names (no slash) are directory excludes; paths
    # containing a slash are file/glob patterns applied after discovery via pathspec.
    ragignore_raw = load_ragignore(project_path)
    ragignore_dir_excludes = {e for e in ragignore_raw if "/" not in e}
    ragignore_path_patterns = [e for e in ragignore_raw if "/" in e]
    excludes = DEFAULT_EXCLUDES | ragignore_dir_excludes

    # Resolve target extensions from language filter
    if languages:
        target_exts: set[str] = set()
        for lang in languages:
            lang_lower = lang.lower()
            if lang_lower in LANGUAGE_EXTENSIONS:
                target_exts |= LANGUAGE_EXTENSIONS[lang_lower]
            else:
                logger.warning("Unknown language filter: %s", lang)
    else:
        target_exts = ALL_CODE_EXTENSIONS

    # --- Tier 1: pathspec (reads .gitignore directly, no subprocess) ---
    # git ls-files was removed — subprocess.run() hangs indefinitely in the
    # MCP subprocess context on Windows even when called from a thread pool,
    # and the timeout mechanism itself fails in that context.
    raw_files, skipped_gitignore = _discover_via_pathspec(root, target_exts, excludes)
    method = "pathspec"

    if raw_files is None:
        # --- Tier 2: plain os.walk ---
        raw_files = _discover_via_walk(root, target_exts, excludes)
        skipped_gitignore = 0
        method = "walk"

    # Apply .ragignore path patterns (e.g. `.claudeboost/knowledge/foo.md`).
    # Directory-name entries are already handled above via excludes; this pass
    # handles entries that contain a slash and therefore refer to specific files
    # or glob patterns that can't be matched by directory pruning alone.
    if ragignore_path_patterns and raw_files:
        try:
            import pathspec as _ps
            ragignore_spec = _ps.PathSpec.from_lines("gitwildmatch", ragignore_path_patterns)
            filtered: list[str] = []
            for abs_path in raw_files:
                rel = str(Path(abs_path).relative_to(root)).replace("\\", "/")
                if ragignore_spec.match_file(rel):
                    skipped_gitignore += 1
                else:
                    filtered.append(abs_path)
            raw_files = filtered
        except Exception as e:
            logger.warning(".ragignore path patterns could not be applied: %s", e)

    logger.info("Discovery method: %s, raw candidates: %d", method, len(raw_files))

    # --- Post-filters ---
    result = ScanResult(skipped_gitignore=skipped_gitignore)
    result.total_discovered = len(raw_files) + skipped_gitignore
    size_kb_total = 0

    for abs_path in raw_files:
        fname = Path(abs_path).name

        # Generated file filter
        if fname in _GENERATED_EXACT or fname.endswith(_GENERATED_SUFFIXES):
            result.skipped_generated += 1
            continue

        # Size filter
        try:
            size_kb = Path(abs_path).stat().st_size / 1024
        except OSError:
            result.skipped_generated += 1
            continue
        if size_kb > max_file_kb:
            result.skipped_too_large += 1
            continue

        size_kb_total += size_kb
        result.files.append(abs_path)

        lang = extension_to_language(Path(abs_path).suffix)
        if lang:
            result.files_by_language[lang] = result.files_by_language.get(lang, 0) + 1

    result.estimated_size_kb = int(size_kb_total)
    logger.info(
        "Scan result: %d files to index, %d skipped (gitignore=%d, too-large=%d, generated=%d)",
        len(result.files),
        result.skipped_gitignore + result.skipped_too_large + result.skipped_generated,
        result.skipped_gitignore, result.skipped_too_large, result.skipped_generated,
    )
    return result


# ---------------------------------------------------------------------------
# Discovery helpers
# ---------------------------------------------------------------------------

def _discover_via_pathspec(
    root: Path, target_exts: set[str], default_excludes: set[str]
) -> tuple[list[str] | None, int]:
    """Use pathspec to respect .gitignore in non-git repos."""
    gitignore_path = root / ".gitignore"
    if not gitignore_path.exists():
        return None, 0

    try:
        import pathspec
    except ImportError:
        logger.warning("pathspec not installed; skipping gitignore parsing")
        return None, 0

    # Load root .gitignore
    lines = gitignore_path.read_text(encoding="utf-8", errors="replace").splitlines()
    spec = pathspec.PathSpec.from_lines("gitwildmatch", lines)

    raw = _discover_via_walk(root, target_exts, default_excludes)
    skipped = 0
    files = []
    for abs_path in raw:
        rel = str(Path(abs_path).relative_to(root)).replace("\\", "/")
        if spec.match_file(rel):
            skipped += 1
        else:
            files.append(abs_path)

    return files, skipped


def _discover_via_walk(
    root: Path, target_exts: set[str], excludes: set[str]
) -> list[str]:
    """Plain os.walk with directory exclusion."""
    files = []
    for dirpath, dirnames, filenames in os.walk(root):
        if excludes:
            dirnames[:] = [d for d in dirnames if d not in excludes]
        for fname in filenames:
            if Path(fname).suffix in target_exts:
                files.append(str(Path(dirpath) / fname))
    return files
